# Generated by Django 6.0 on 2025-12-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_createaccountrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccountrequest',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
